baseURL = "http://dorfingerjonas.at/"
title = "Jonas Dorfinger"
theme = "dorfingerjonas"
themeDir = "./themes/"

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true